### PR TITLE
Fixed DTK_LIBRARIES patch issue

### PR DESCRIPTION
**Pull request by fcollot**
The ```DTK_LIBRARIES``` variable was faulty because it contained ```dtkComposer``` even when the composer plugin wasn't built, causing linker issues.
(Note: to activate the actual compilation of the DTK composer plugin, you have to activate the DTK_BUILD_COMPOSER option in the _projects_ workspace of QT Creator for DTK, or through ccmake)

### CODE REVIEW

**Comment by mathildemerle** [comment]
Are you ok with 2 patches on DTK ? It could be combined in the future into only one, i could do that if needed

**Review by mathildemerle — APPROVED** [review]

**Review by juliencastelneau — APPROVED** [review]

**Comment by fcollot** [comment]
In general existing patches shouldn't be modified as it breaks patching for people who have already applied them. For example, if someone has already applied the first DTK patch, and we replace it with a combined one, the combined one will not be applied on their installation, leaving their DTK in a faulty state.

**Comment by fcollot** [comment]
(Modifying an existing patch is the equivalent of modifying a commit that has already been merged. You should instead make a revert commit)

**Comment by mathildemerle** [comment]
Well, there are pro and cons, but if we accumulate a lot of patches for one library, it could be more and more complicated to understand what's done on the library. But indeed for dev, we do not need to `git stash` (for instance) the library, and recompile. However, since we're a few to actively work on the code, i thought it could be easier to use only one patch on a library topic (multiples patches if they have completely separated uses, and changes separated files)

**Pull request merged**
