### PR TITLE
Package description for Linux

### PR DESCRIPTION
**Pull request by mathildemerle**
(Need https://github.com/Inria-Asclepios/medinria-superproject/pull/3)

This PR changes the description & name of the linux package.

### CODE REVIEW

**Comment by mathildemerle** [comment]
Done, @LoicCadour i've updated the linux installer filenames :)

**Comment by LoicCadour** [comment]
OK

**Comment by LoicCadour** [comment]
Let Jenkins be the second reviewer!
I merge and if the result is not satisfying, i'll un-merge.

**Comment by LoicCadour** [comment]
Package renaming works!

**Pull request merged**
