### PR TITLE
gets medInria from Inria-Asclepios repo

### PR DESCRIPTION
**Pull request by LoicCadour**

### CODE REVIEW

**Comment by mathildemerle** [comment]
Parfait !

**Comment by fcollot** [comment]
good

**Comment by msermesant** [comment]
medInria is now switching the master to the new refactored version, but there should be a branch with the older version, we should point to it, no?

**Comment by LoicCadour** [comment]
Actually we have our own branch of medInria, which gathers some plugins, some MUSIC personalisation, some hacks, ...

**Pull request merged**
