### PR TITLE
[binaries] solves missing files in linux binaries

### PR DESCRIPTION
**Pull request by mathildemerle**
This allow to create a package under linux. Tested on Ubuntu.

### CODE REVIEW

**Comment by LoicCadour** [comment]
Well done.

**Comment by LoicCadour** [comment]
I merge it to test the compilation tonight.
Then I'll send you the installer to test it :)
If it's not working, I will un-merge it

**Comment by LoicCadour** [comment]
It solves the pb.
So if @mathildemerle and @fcollot agree, let's keep it merged.

**Comment by mathildemerle** [comment]
I agreeeee <3

**Pull request merged**
